
spring.profiles.active = dev
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.access.expiration-ms=900000
jwt.refresh.expiration-ms=604800000

spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false