server.port=8080

spring.datasource.url=jdbc:postgresql://ep-winter-darkness-aohx5p9y-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_deSL0hHBJ4oz
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true

jwt.secret=8f2d4a6e1b3c9d7f0e5a2b8c4d6f1e3a7b9c0d2e4f6a8b1c3d5e7f9a0b2c4d6