server.port=8080

spring.datasource.url=jdbc:postgresql://dpg-d6t6qivkijhs73eu3t3g-a.singapore-postgres.render.com:5432/sportsconnect
spring.datasource.username=sportsconnect_user
spring.datasource.password=xix30Mok6LacK7oAsiaMDD0w20HNycQZ
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true

jwt.secret=8f2d4a6e1b3c9d7f0e5a2b8c4d6f1e3a7b9c0d2e4f6a8b1c3d5e7f9a0b2c4d6